# Generated by Django 4.0.6 on 2022-07-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('made_in', models.CharField(choices=[('USA', 'United States'), ('EN', 'English'), ('KG', 'Kyrgyzstan'), ('KZ', 'Kazakhstan'), ('UZ', 'Uzbekstan'), ('CN', 'China'), ('KR', 'Korea')], max_length=50)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='amazon.catalogs')),
            ],
        ),
    ]
